<?php


namespace app\admin\controller;


use think\Controller;
use think\exception\HttpResponseException;

class Admin extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $admin = session('admin');
        // 这里的session 是当用户登录成功后创建的一个session 如果没有的话就代表没有用户登录
        // var_dump($uid);
        if($admin == null || $admin == "" || $admin == "null" || $admin == 0){
            throw new HttpResponseException(error("未登录"));
        }
    }

}